const listsData = {
  states: [
    { code: "AL", stateName: "Alabama" },
    { code: "AK", stateName: "Alaska" },
    { code: "AZ", stateName: "Arizona" },
    { code: "AR", stateName: "Arkansas" },
    { code: "CA", stateName: "California" },
    { code: "CO", stateName: "Colorado" },
    { code: "CT", stateName: "Connecticut" },
    { code: "DE", stateName: "Delaware" },
    { code: "DC", stateName: "District of Columbia" },
    { code: "FL", stateName: "Florida" },
    { code: "GA", stateName: "Georgia" },
    { code: "HI", stateName: "Hawaii" },
    { code: "ID", stateName: "Idaho" },
    { code: "IL", stateName: "Illinois" },
    { code: "IN", stateName: "Indiana" },
    { code: "IA", stateName: "Iowa" },
    { code: "KS", stateName: "Kansas" },
    { code: "KY", stateName: "Kentucky" },
    { code: "LA", stateName: "Louisiana" },
    { code: "ME", stateName: "Maine" },
    { code: "MD", stateName: "Maryland" },
    { code: "MA", stateName: "Massachusetts" },
    { code: "MI", stateName: "Michigan" },
    { code: "MN", stateName: "Minnesota" },
    { code: "MS", stateName: "Mississippi" },
    { code: "MO", stateName: "Missouri" },
    { code: "MT", stateName: "Montana" },
    { code: "NE", stateName: "Nebraska" },
    { code: "NV", stateName: "Nevada" },
    { code: "NH", stateName: "New Hampshire" },
    { code: "NJ", stateName: "New Jersey" },
    { code: "NM", stateName: "New Mexico" },
    { code: "NY", stateName: "New York" },
    { code: "NC", stateName: "North Carolina" },
    { code: "ND", stateName: "North Dakota" },
    { code: "OH", stateName: "Ohio" },
    { code: "OK", stateName: "Oklahoma" },
    { code: "OR", stateName: "Oregon" },
    { code: "PA", stateName: "Pennsylvania" },
    { code: "RI", stateName: "Rhode Island" },
    { code: "SC", stateName: "South Carolina" },
    { code: "SD", stateName: "South Dakota" },
    { code: "TN", stateName: "Tennessee" },
    { code: "TX", stateName: "Texas" },
    { code: "UT", stateName: "Utah" },
    { code: "VT", stateName: "Vermont" },
    { code: "VA", stateName: "Virginia" },
    { code: "WA", stateName: "Washington" },
    { code: "WV", stateName: "West Virginia" },
    { code: "WI", stateName: "Wisconsin" },
    { code: "WY", stateName: "Wyoming" }
  ],

  specialties: [
    "Airlines/Aviation",
    "Alternative Dispute Resolution",
    "Alternative Medicine",
    "Animation",
    "Apparel & Fashion",
    "Architecture & Planning",
    "Arts and Crafts",
    "Automotive",
    "Aviation & Aerospace",
    "Banking",
    "Biotechnology",
    "Broadcast Media",
    "Building Materials",
    "Business",
    "Business Administration",
    "Business Supplies and Equipment",
    "Capital Markets",
    "Chemicals",
    "Civic & Social Organization",
    "Civil Engineering",
    "Commercial Real Estate",
    "Computer & Network Security",
    "Computer Science",
    "Computer Games",
    "Computer Hardware",
    "Computer Networking",
    "Computer Software",
    "Construction",
    "Consumer Electronics",
    "Consumer Goods",
    "Consumer Services",
    "Cosmetics",
    "Creative Director and Designer",
    "Dairy",
    "Defense & Space",
    "Design",
    "Education",
    "E-Learning",
    "Electrical/Electronic Manufacturing",
    "Entertainment",
    "Entrepreneur",
    "Environmental Services",
    "Events Services",
    "Executive Office",
    "Facilities Services",
    "Farming",
    "Finance",
    "Financial Services",
    "Fine Art",
    "Fishery",
    "Food & Beverages",
    "Food Production",
    "Fund-Raising",
    "Furniture",
    "Gambling & Casinos",
    "Glass, Ceramics & Concrete",
    "Government Administration",
    "Government Relations",
    "Graphic Design",
    "Health, Wellness and Fitness",
    "Higher Education",
    "Hospital & Health Care",
    "Hospitality",
    "Human Resources",
    "Import and Export",
    "Individual & Family Services",
    "Industrial Automation",
    "Information Services",
    "Information Technology and Services",
    "Insurance",
    "International Affairs",
    "International Trade and Development",
    "Internet",
    "Investment Banking",
    "Investment Management",
    "Judiciary",
    "Law Enforcement",
    "Law Practice",
    "Legal Services",
    "Legislative Office",
    "Leisure, Travel & Tourism",
    "Libraries",
    "Logistics and Supply Chain",
    "Jewelry",
    "Machinery",
    "Management Consulting",
    "Maritime",
    "Market Research",
    "Marketing and Advertising",
    "Mechanical or Industrial Engineering",
    "Media",
    "Media Production",
    "Medical Devices",
    "Medical Practice",
    "Mental Health Care",
    "Military",
    "Mining & Metals",
    "Motion Pictures and Film",
    "Museums and Institutions",
    "Music",
    "Nanotechnology",
    "Newspapers",
    "Non-Profit Organization Management",
    "Oil & Energy",
    "Online Media",
    "Outsourcing/Offshoring",
    "Package/Freight Delivery",
    "Packaging and Containers",
    "Paper & Forest Products",
    "Performing Arts",
    "Pharmaceuticals",
    "Philanthropy",
    "Photography",
    "Plastics",
    "Political Organization",
    "Portuguese Community",
    "Primary/Secondary Education",
    "Printing",
    "Professional Training & Coaching",
    "Professor",
    "Program Development",
    "Public Policy",
    "Public Relations and Communications",
    "Public Safety",
    "Publishing",
    "Railroad Manufacture",
    "Ranching",
    "Real Estate",
    "Recreational Facilities and Services",
    "Religious Institutions",
    "Renewables & Environment",
    "Research",
    "Restaurants",
    "Retail",
    "Security and Investigations",
    "Semiconductors",
    "Shipbuilding",
    "Social Media",
    "Speaker",
    "Sporting Goods",
    "Sports",
    "Staffing and Recruiting",
    "Supermarkets",
    "Telecommunications",
    "Textiles",
    "Think Tanks",
    "Tobacco",
    "Translation and Localization",
    "Transportation/Trucking/Railroad",
    "Utilities",
    "Venture Capital & Private Equity",
    "Veterinary",
    "Warehousing",
    "Wholesale",
    "Wine and Spirits",
    "Wireless",
    "Writing and Editing"
  ]
};

export default listsData;
